create or replace view V_SND_PROC as
SELECT ID,
         WORKDATE,
         PKG_ID,
         'HVPS' AS SYS_CODE,
         'hvps.111.001.01' AS Msg_Type,
         BIZ_TYPE_CODE,
         BIZ_CTGY_CODE,
         STATUS,
         AMOUNT
FROM CP2_HVPS111
WHERE DRCT = '1'
UNION ALL
SELECT ID,
       WORKDATE,
       PKG_ID,
       'HVPS' AS SYS_CODE,
       'hvps.112.001.01' AS Msg_Type,
       BIZ_TYPE_CODE,
       BIZ_CTGY_CODE,
       STATUS,
       AMOUNT
FROM CP2_HVPS112
WHERE DRCT = '1'
UNION ALL
Select Id,
       WORKDATE,
       PKG_ID,
       'BEPS' AS SYS_CODE,
       'beps.121.001.01' AS Msg_Type,
       BIZ_TYPE_CODE,
       BIZ_CTGY_CODE,
       STATUS,
       AMOUNT
FROM CP2_BEPS121
Where DRCT = '1'
UNION ALL
Select Id,
       WORKDATE,
       PKG_ID,
       'BEPS' AS SYS_CODE,
       'beps.122.001.01' AS Msg_Type,
       BIZ_TYPE_CODE,
       BIZ_CTGY_CODE,
       STATUS,
       AMOUNT
FROM CP2_BEPS122
WHERE DRCT = '1'
UNION ALL
Select Id,
       WORKDATE,
       PKG_ID,
       'HVPS' AS SYS_CODE,
       'hvps.115.001.01' AS Msg_Type,
       BIZ_TYPE_CODE,
       BIZ_CTGY_CODE,
       STATUS,
       AMOUNT
FROM CP2_HVPS115_001
WHERE DRCT = '1'
/

 create or replace view V_NSTP_OUTCOMMIN as
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS' AS SYS_CODE,
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.MEMO||H.MEMO2 AS VARCHAR(512)) AS REMARKS,
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_BRNAME,
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_ST_BRNAME,
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_BRNAME,
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_ST_BRNAME,
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME
FROM
    CP2_HVPS111 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '1'
UNION ALL
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS',
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.REMARKS||H.REMARKS2 AS VARCHAR(512)),
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME
FROM
    CP2_HVPS112 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '1'
UNION ALL
SELECT
    B.ID,
    B.PKG_ID,
    B.WORKDATE,
    T.VDATE,
    'BEPS',
    B.PKG_NO,
    B.BIZ_TYPE_CODE,
    B.BIZ_CTGY_CODE,
    B.CURCD,
    B.AMOUNT,
    B.REMARK,
    B.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    B.SND_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ACC_BRNO,
    B.PAYER_ACC_BRNAME,
    B.PAYEE_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    B.RCV_ST_BRNO,
    CAST(BN5.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ACC_BRNO,
    B.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    M.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    B.PAYER_ACTNO,
    B.PAYER_NAME,
    B.PAYEE_ACTNO,
    B.PAYEE_NAME
FROM
    CP2_BEPS121 B
INNER JOIN
    CP2_TXN T
ON
    B.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_BEPSBTMNG M
ON
    B.BT_ID = M.ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = B.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = B.SND_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = B.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN5
ON
    BN5.BANK_CODE = B.RCV_ST_BRNO
WHERE
    T.DRCT = '1'
UNION ALL
SELECT
    B.ID,
    B.PKG_ID,
    B.WORKDATE,
    T.VDATE,
    'BEPS',
    B.PKG_NO,
    B.BIZ_TYPE_CODE,
    B.BIZ_CTGY_CODE,
    B.CURCD,
    B.AMOUNT,
    B.REMARK,
    B.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    B.SND_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ACC_BRNO,
    B.PAYER_ACC_BRNAME,
    B.PAYEE_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    B.RCV_ST_BRNO,
    CAST(BN5.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ACC_BRNO,
    B.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    M.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    B.PAYER_ACTNO,
    B.PAYER_NAME,
    B.PAYEE_ACTNO,
    B.PAYEE_NAME
FROM
    CP2_BEPS122 B
INNER JOIN
    CP2_TXN T
ON
    B.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_BEPSBTMNG M
ON
    B.BT_ID = M.ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = B.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = B.SND_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = B.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN5
ON
    BN5.BANK_CODE = B.RCV_ST_BRNO
WHERE
    T.DRCT = '1'
UNION ALL
SELECT
    B.ID,
    B.PKG_ID,
    B.WORKDATE,
    T.VDATE,
    'BEPS',
    B.PKG_NO,
    B.BIZ_TYPE_CODE,
    B.BIZ_CTGY_CODE,
    B.CURCD,
    B.AMOUNT,
    B.REMARK||B.REMARK2,
    B.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ACC_BRNO,
    B.PAYER_ACC_BRNAME,
    B.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ACC_BRNO,
    B.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    M.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    B.PAYER_ACTNO,
    B.PAYER_NAME,
    B.PAYEE_ACTNO,
    B.PAYEE_NAME
FROM
    CP2_BEPS125 B
INNER JOIN
    CP2_TXN T
ON
    B.ID = T.CORE_ID
INNER JOIN
    CP2_BEPSBTMNG M
ON
    B.BT_ID = M.ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = B.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = B.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = B.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = B.PAYEE_ST_BRNO
WHERE
    T.DRCT = '1'
UNION ALL
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS' AS SYS_CODE,
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.REMARKS||H.REMARKS2 AS VARCHAR(512)) AS REMARKS,
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_BRNAME,
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_ST_BRNAME,
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_BRNAME,
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_ST_BRNAME,
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME
FROM
    CP2_HVPS115_001 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '1'
/

create or replace view V_NSTP_INCOMMIN_ALL as
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS' AS SYS_CODE,
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.MEMO||H.MEMO2 AS VARCHAR(512)) AS REMARKS,
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_BRNAME,
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_ST_BRNAME,
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_BRNAME,
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_ST_BRNAME,
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO AS NSTP_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME AS NSTP_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO AS NSTP_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME,
    H.RETURN_REASON AS RETURN_REASON
FROM
    CP2_HVPS111 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '2'
UNION ALL
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS',
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.REMARKS||H.REMARKS2 AS VARCHAR(512)),
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO AS NSTP_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME AS NSTP_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO AS NSTP_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME,
    H.RETURN_REASON AS RETURN_REASON
FROM
    CP2_HVPS112 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '2'
UNION ALL
SELECT
    B.ID,
    B.PKG_ID,
    B.WORKDATE,
    T.VDATE,
    'BEPS',
    B.PKG_NO,
    B.BIZ_TYPE_CODE,
    B.BIZ_CTGY_CODE,
    B.CURCD,
    B.AMOUNT,
    B.REMARK,
    B.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    B.SND_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ACC_BRNO,
    B.PAYER_ACC_BRNAME,
    B.PAYEE_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    B.RCV_ST_BRNO,
    CAST(BN5.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ACC_BRNO,
    B.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    M.RCV_TIME,
    T.ORI_PAYEE_ACTNO AS NSTP_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME AS NSTP_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO AS NSTP_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    B.PAYER_ACTNO,
    B.PAYER_NAME,
    B.PAYEE_ACTNO,
    B.PAYEE_NAME,
    B.RETURN_CONTENT AS RETURN_REASON
FROM
    CP2_BEPS121 B
INNER JOIN
    CP2_TXN T
ON
    B.ID = T.CORE_ID
INNER JOIN
    CP2_BEPSBTMNG M
ON
    B.BT_ID = M.ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = B.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = B.SND_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = B.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN5
ON
    BN5.BANK_CODE = B.RCV_ST_BRNO
WHERE
    T.DRCT = '2'
UNION ALL
SELECT
    B.ID,
    B.PKG_ID,
    B.WORKDATE,
    T.VDATE,
    'BEPS',
    B.PKG_NO,
    B.BIZ_TYPE_CODE,
    B.BIZ_CTGY_CODE,
    B.CURCD,
    B.AMOUNT,
    B.REMARK,
    B.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)),
    B.SND_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYER_ACC_BRNO,
    B.PAYER_ACC_BRNAME,
    B.PAYEE_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)),
    B.RCV_ST_BRNO,
    CAST(BN5.ORG_FULLNAME AS VARCHAR (180)),
    B.PAYEE_ACC_BRNO,
    B.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    M.RCV_TIME,
    T.ORI_PAYEE_ACTNO AS NSTP_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME AS NSTP_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO AS NSTP_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    B.PAYER_ACTNO,
    B.PAYER_NAME,
    B.PAYEE_ACTNO,
    B.PAYEE_NAME,
    B.RETURN_REASON AS RETURN_REASON
FROM
    CP2_BEPS122 B
INNER JOIN
    CP2_TXN T
ON
    B.ID = T.CORE_ID
INNER JOIN
    CP2_BEPSBTMNG M
ON
    B.BT_ID = M.ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = B.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = B.SND_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = B.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN5
ON
    BN5.BANK_CODE = B.RCV_ST_BRNO
WHERE
    T.DRCT = '2'
UNION ALL
SELECT
    H.ID,
    H.PKG_ID,
    H.WORKDATE,
    T.VDATE,
    'HVPS' AS SYS_CODE,
    H.PKG_NO,
    H.BIZ_TYPE_CODE,
    H.BIZ_CTGY_CODE,
    H.CURCD,
    H.AMOUNT,
    CAST(H.REMARKS||H.REMARKS2 AS VARCHAR(512)) AS REMARKS,
    H.PAYER_BRNO,
    CAST(BN1.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_BRNAME,
    H.PAYER_ST_BRNO,
    CAST(BN2.ORG_FULLNAME AS VARCHAR (180)) AS PAYER_ST_BRNAME,
    H.PAYER_ACC_BRNO,
    H.PAYER_ACC_BRNAME,
    H.PAYEE_BRNO,
    CAST(BN3.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_BRNAME,
    H.PAYEE_ST_BRNO,
    CAST(BN4.ORG_FULLNAME AS VARCHAR (180)) AS PAYEE_ST_BRNAME,
    H.PAYEE_ACC_BRNO,
    H.PAYEE_ACC_BRNAME,
    T.NSTP_TYPE,
    T.NSTP_OPTYPE,
    T.NSTP_REMARKS,
    H.RCV_TIME,
    T.ORI_PAYEE_ACTNO AS NSTP_PAYEE_ACTNO,
    T.ORI_PAYEE_ACTNAME AS NSTP_PAYEE_ACTNAME,
    T.ORI_PAYEE_BRNO AS NSTP_PAYEE_BRNO,
    T.STATUS,
    T.BRNO,
    T.MD_TLRNO,
    T.MD_TIME,
    T.CK_TLRNO,
    T.CK_TIME,
    T.AUD_TLRNO,
    T.AUD_TIME,
    T.SOURCE,
    H.PAYER_ACTNO,
    H.PAYER_NAME,
    H.PAYEE_ACTNO,
    H.PAYEE_NAME,
    H.RETURN_REASON AS RETURN_REASON
FROM
    CP2_HVPS115_001 H
INNER JOIN
    CP2_TXN T
ON
    H.ID = T.CORE_ID
LEFT OUTER JOIN
    CP2_CNAPSBANK BN1
ON
    BN1.BANK_CODE = H.PAYER_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN2
ON
    BN2.BANK_CODE = H.PAYER_ST_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN3
ON
    BN3.BANK_CODE = H.PAYEE_BRNO
LEFT OUTER JOIN
    CP2_CNAPSBANK BN4
ON
    BN4.BANK_CODE = H.PAYEE_ST_BRNO
WHERE
    T.DRCT = '2'
/


